### ISSUE TITLE
'follow this guide' link dead

### ISSUE THREAD

**Issue by Cale-Torino** [shuuryou/texmond#1]
The link is dead I will suggest using these other similar links.

https://universaldiscoverymethodology.com/2015/04/07/com-usb-alternative-diy-and-cheap/

or

https://cybergibbons.com/alarms-2/programming-a-texecom-premier-elite-12-w-using-a-ftdi-cable/

**Comment by shuuryou** [comment]
Thanks for letting me know. I just checked, and the link it points to (https://archive.ph/jjMXk) seems to be working as of right now. The "Archive.today" service is blocked by some ISPs and sometimes goes down.

The archive link is just copy of the second link (cybergibbons.com) you posted though. I don't like linking to blogs directly because they have a tendency to disappear or change their content randomly.
